portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # /projects
    path('projects/', include('projects_app.urls') )
]

projects_app/urls.py
from django.urls import path
from projects_app import views
app_name = "projects_app"  # need to be present for django to identify app
urlpatterns = [
    path('', views.all_projects, name="all_projects"),
    path('<int:pk>', views.project_detail, name="project_detail"),
]

projects_app/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

projects_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from projects_app.models import Project

# Create your views here.


def all_projects(request):
    # query the database
    projects = Project.objects.all()
    return render(request, 'projects_app/all_projects.html', {'projects': projects})


def project_detail(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, 'projects_app/details.html', {'project': project})

projects_app/templates/projects_app/all_projects.html
{% extends 'projects_app/base.html' %}
{% load static %}

{% block content %}

<h1>Projects</h1>
<div class="row">
    {% for project in projects %}
    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{% static project.image %}">
            <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                <a href="{% url 'projects_app:project_detail' project.pk %}" class="btn btn-primary">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

projects_app/templates/projects_app/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'projects_app:all_projects' %}">Portfolio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'projects_app:all_projects' %}">Home</a>
                    </li>

                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-disabled="true"
                        aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

projects_app/templates/projects_app/details.html
{% extends 'projects_app/base.html' %}
{% load static %}

{% block content %}
<h1>{{project.title}}</h1>
<div class="col-md-8">
    <img class="card-img-top" src="{% static project.image %}" alt="{{ project.description }}">
</div>
<div class="col-md-4">
    <h5>About</h5>
    <p>{{project.description}}</p>
    <h5>Built with:</h5>
    <p>{{project.technology}}</p>
</div>

{% endblock %}